{% set name = "geckodriver" %}
{% set version = "0.27.0" %}
{% set min_firefox = "60" %}

# this is published in short form on the github release page
{% set changeset = "90ec81285ff6287cb2824b29ddebb7818cc7b96b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-{{ changeset }}.zip
  # all of /testing because of other unpublished crates
  url: https://hg.mozilla.org/mozilla-central/archive/{{ changeset }}.zip/testing
  sha256: 4809d4a181e33796488d8481120427c717e54e3deedccb253a3bdbf2dc931c76

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust
    - sysroot_linux-64 2.17  # [linux64]
    # only for license checking
    - python >=3.6  # [unix]
    - ruamel_yaml  # [unix]

test:
  requires:
    - firefox >={{ min_firefox }}
    - pytest-azurepipelines
    - python >=3.6
    - selenium
  commands:
    - geckodriver --version
    - geckodriver --help
    # this important just so we know that the version is accurate
    # https://github.com/mozilla/geckodriver/issues/1615
    - geckodriver --version | grep {{ version }}  # [not win]
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
    - copy {{ RECIPE_DIR }}\test_selenium.py .  # [win]
    - copy {{ RECIPE_DIR }}\setup.cfg .  # [win]
    - cp {{ RECIPE_DIR }}/test_selenium.py {{ RECIPE_DIR }}/setup.cfg .  # [not win]
    # TODO: may be needed
    # - set -m && % xattr -r -d com.apple.quarantine $PREFIX/bin/geckodriver  # [osx]
    - python -m pytest

about:
  home: https://github.com/mozilla/geckodriver
  license: MPL-2.0
  # non of the above actually include the license
  # BEGIN license_file
  license_file:
    - 'library_licenses/geckodriver-MPL-2.0.txt'
  # END license_file
  summary: |
    geckodriver is a proxy for using W3C WebDriver-compatible clients to
    interact with Gecko-based browsers.
  description: |
    This program provides the HTTP API described by the WebDriver protocol to
    communicate with Gecko browsers, such as Firefox. It translates calls into
    the Marionette remote protocol by acting as a proxy between the local- and
    remote ends.
  doc_url: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver
  dev_url: https://searchfox.org/mozilla-central/source/testing/geckodriver

extra:
  recipe-maintainers:
    - bollwyvl
