{% set name = "geckodriver" %}
{% set version = "0.26.0" %}
{% set changeset = "e9783a644016aa9b317887076618425586730d73" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # doesn't contain anything useful, but mozilla-central has no symbolic tags
  # for geckodriver releases so there isn't anything for the bot to find
  - url: https://github.com/mozilla/geckodriver/archive/v{{ version }}.tar.gz
    sha256: c6acabacf8063ff59926f6b8721968a6eaaa35050b2988868a2d8d37ef7c90dd
    folder: just-for-the-bot-to-find-updates-properly
  # needs an fn because of the unique URL structure
  - fn: {{ name }}-{{ version }}-{{ changeset }}.tar.gz
    # all of /testing because of other crates which no longer get published (?)
    url: https://hg.mozilla.org/mozilla-central/archive/{{ changeset }}.tar.gz/testing
    sha256: 2f8357062af904e43c10afbfb0387c11eeb48722267a81bad87aacc6ec835e70

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust

test:
  downstreams:
    - firefox  >=60
  commands:
    - geckodriver --version
    - geckodriver --help
    # this important just so we know that the version is accurate
    # https://github.com/mozilla/geckodriver/issues/1615
    - geckodriver --version | grep {{ version }}  # [not win]
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: https://github.com/mozilla/geckodriver
  license: MPL-2.0
  # non of the above actually include the license
  license_file: '{{ environ["RECIPE_DIR"] }}/mpl-2.0.txt'
  summary: |
    geckodriver is a proxy for using W3C WebDriver-compatible clients to
    interact with Gecko-based browsers.
  description: |
    This program provides the HTTP API described by the WebDriver protocol to
    communicate with Gecko browsers, such as Firefox. It translates calls into
    the Marionette remote protocol by acting as a proxy between the local- and
    remote ends.
  doc_url: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver
  dev_url: https://searchfox.org/mozilla-central/source/testing/geckodriver

extra:
  recipe-maintainers:
    - bollwyvl
