{% set name = "geckodriver" %}
{% set version = "0.27.0" %}
{% set changeset = "09dbca8803460053ac9a3b89d9e049065df1c963" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-{{ changeset }}.zip
  # all of /testing because of other crates which no longer get published (?)
  url: https://hg.mozilla.org/mozilla-central/archive/{{ changeset }}.zip/testing
  sha256: c2078f3d529c88288bc0856f23bc53e9a5fce88136c529e99c7bc10872891f62

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust

test:
  downstreams:
    - firefox >=60
  commands:
    - geckodriver --version
    - geckodriver --help
    # this important just so we know that the version is accurate
    # https://github.com/mozilla/geckodriver/issues/1615
    - geckodriver --version | grep {{ version }}  # [not win]
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: https://github.com/mozilla/geckodriver
  license: MPL-2.0
  # non of the above actually include the license
  license_file: '{{ environ["RECIPE_DIR"] }}/mpl-2.0.txt'
  summary: |
    geckodriver is a proxy for using W3C WebDriver-compatible clients to
    interact with Gecko-based browsers.
  description: |
    This program provides the HTTP API described by the WebDriver protocol to
    communicate with Gecko browsers, such as Firefox. It translates calls into
    the Marionette remote protocol by acting as a proxy between the local- and
    remote ends.
  doc_url: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver
  dev_url: https://searchfox.org/mozilla-central/source/testing/geckodriver

extra:
  recipe-maintainers:
    - bollwyvl
