# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hy9BzaApnFPNsRxjzr6mPXwdLzQoa51uIyDPRiFGlQ8atpGDapHOiBuMLNjNflCpnZ4Mn521+Rn8gaI1aNgAH+BAWERk0P2gUZUQQHRWH68g4AxqcvJxbmapYz6xhLP/vV9tAEN1SRhhY+jX8ZsXJzRLeYDeO7DZkeKO3+wpfhyUa+tsF8WLjHOGPeo6Dzy+8GFdiVilno1/rMbk+KeOOrsK84AVeDWsAdvmOxmQ27zpO4XlPRP3FTZoQihfwR8zgyubb3EC6+6sXCKoPVGMJepvlPjBMAIi8d1/oyvH9jJKZ2EyFLV+PPCKtEb9uun1yvY8eVJznPZKNVPO9PKpuHtYbX0y2q9pBpDDeAZ84Qp24HK9Vq8QBzPBzjo7SwMuYz09rIEQYtj2+xxNxWm7d1Ro9hXokgtsskLb4T6OCus8rNyllkR0LTlTHW3SospVsoTY4ptly4OqogiIU6KqQQI/dLH0BcBUQWl1+Lc0+NlXe9V63HEO1yVO6jDv7yGABAiLpx7EB65eMHVJKy5AEKl16kUo44FyhJKy/PtOTWjEtqAbTr/RXV0wFyoentRV7wpo21QQYWhjyjvd7GxNNK2xejI6JZHcvyHyhFL56LR7uZWDC1Rh0g1LtDlEm2Y3+WTseVSkp8ACOGgDjzAd1GNPIkmlYje3TMth5fMBQRc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
