travis:
  secure:
    BINSTAR_TOKEN: gesRt/myI9sfVLer+WStFtWuLCirdmN1u82ilCpKIDVMx9hyFbEdk69BYP4X8DuXRVnh/dojKib7ZhIYvNTLiQa5NiuxlJcb1Xv4kF/hoDB3bu1s5ZtT23qiYfUp0a9wURF6q3tOq2Hv0oDFpk9oZV5E3j1jDiJXHERbEdYic2sR1BGKT4upZr+LWpmjx+o9V/UtvaqNVgI9a88ryj2O4OtPnywiu9ccYmjxBQvBS+UQs+f+/5nX4dpGaBlpsxaxkiLmxGPk+ztVbH1qtfrqrFDbM7QiyI9v75gwdOWDHhIu7o7ZDmTN7boy9MkR2GnT3BNVAhm/K+SVf5rRLzWcBKlAmU0CjeyiPu3BIzpwUSY4EewuernQxaXTYzMuPyY8wIymu4C5fYJPXcWSTRBjPwYh1k5IJ3vSYIVn4OosQlFi6l+3x964i6l0nBkeaIaAdviRPLQQ/mUsL+nccfpCKCUazeydxeIW5D5B4VHeW2mPPYdWpRS4XpszayLTVU4MBQpfN0W7zSDqom6kprUtKA0STaCMTHkdQYvHgbW3eZAvW2c6yYmp627p7hvQlQkCaiBbs7iE0g0EQ0H2t+ROEuczUGgphY5/Yabq4MRaPD0urpnZXjodMawkYNjZm2mrDqD6zN0tiFdjGE6f4i690mulT7Qmjgt9LKba2pW/5JQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
