travis:
  secure:
    BINSTAR_TOKEN: hy9BzaApnFPNsRxjzr6mPXwdLzQoa51uIyDPRiFGlQ8atpGDapHOiBuMLNjNflCpnZ4Mn521+Rn8gaI1aNgAH+BAWERk0P2gUZUQQHRWH68g4AxqcvJxbmapYz6xhLP/vV9tAEN1SRhhY+jX8ZsXJzRLeYDeO7DZkeKO3+wpfhyUa+tsF8WLjHOGPeo6Dzy+8GFdiVilno1/rMbk+KeOOrsK84AVeDWsAdvmOxmQ27zpO4XlPRP3FTZoQihfwR8zgyubb3EC6+6sXCKoPVGMJepvlPjBMAIi8d1/oyvH9jJKZ2EyFLV+PPCKtEb9uun1yvY8eVJznPZKNVPO9PKpuHtYbX0y2q9pBpDDeAZ84Qp24HK9Vq8QBzPBzjo7SwMuYz09rIEQYtj2+xxNxWm7d1Ro9hXokgtsskLb4T6OCus8rNyllkR0LTlTHW3SospVsoTY4ptly4OqogiIU6KqQQI/dLH0BcBUQWl1+Lc0+NlXe9V63HEO1yVO6jDv7yGABAiLpx7EB65eMHVJKy5AEKl16kUo44FyhJKy/PtOTWjEtqAbTr/RXV0wFyoentRV7wpo21QQYWhjyjvd7GxNNK2xejI6JZHcvyHyhFL56LR7uZWDC1Rh0g1LtDlEm2Y3+WTseVSkp8ACOGgDjzAd1GNPIkmlYje3TMth5fMBQRc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
